module.exports = {
  someSidebar: [
    {
      type: 'doc',
      id: 'getting_started',
    },
    {
      type: 'doc',
      id: 'integrations/cicd',
    },
    {
      type: 'category',
      label: 'Open source features',
      collapsed: false,
      items: [
        'features/cli_commands',
        'features/config_file',
        'features/usage_based_resources',
        'features/terraform_modules',
        'features/terragrunt',
        'features/share_links',
        'features/environment_variables',
      ],
    },
    {
      type: 'category',
      label: 'Infracost Cloud features',
      collapsed: false,
      items: [
        'infracost_cloud/get_started',
        'infracost_cloud/finops_policies',
        'infracost_cloud/tagging_policies',
        'infracost_cloud/guardrails',
        'infracost_cloud/jira_integration',
        'infracost_cloud/reports',
        'infracost_cloud/data_export',
        'infracost_cloud/custom_price_books',
        'infracost_cloud/actual_costs',
        'infracost_cloud/readme_badge',
        'infracost_cloud/key_concepts',
        'infracost_cloud/sso',
      ],
    },
    {
      type: 'category',
      label: 'Integrations',
      collapsed: true,
      items: [
        'integrations/github_app',
        'integrations/gitlab_app',
        'integrations/github_actions',
        'integrations/gitlab_ci',
        'integrations/atlantis',
        'integrations/azure_pipelines',
        'integrations/generic_cicd',
        'integrations/terraform_cloud_enterprise',
        'integrations/vscode',
        'integrations/open_policy_agent',
        'integrations/slack',
        'integrations/infracost_api',
        'integrations/third_party_integrations',
      ],
    },
    {
      type: 'category',
      label: 'Supported clouds',
      collapsed: true,
      items: [
        `supported_resources/overview`,
        'supported_resources/aws',
        'supported_resources/azure',
        'supported_resources/google',
      ],
    },
    {
      type: 'category',
      label: 'Cloud Pricing API',
      collapsed: true,
      items: [
        'cloud_pricing_api/api_usage',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsed: true,
      items: [
        'guides/source_control_benefits',
        'guides/v0.10_migration',
        'guides/v0.9_migration',
        'guides/v0.8_migration',
        'guides/actions_migration',
        'guides/gitlab_ci_migration',
        'guides/atlantis_migration',
        'guides/azure_devops_migration',
        'guides/uninstall',
      ],
    },
    {
      type: 'doc',
      id: 'faq',
    },
    {
      type: 'doc',
      id: 'troubleshooting',
    },
  ]
};
